Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/orderer.tpsr.com/msp
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    OrdererEndpoints:
      - orderer0.orderer.tpsr.com:7050

  - &VendorOrg
    Name: VendorOrg
    ID: VendorMSP
    MSPDir: crypto-config/peerOrganizations/vendor.tpsr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('VendorMSP.admin', 'VendorMSP.peer', 'VendorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('VendorMSP.admin', 'VendorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('VendorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('VendorMSP.member')"
    AnchorPeers:
      - Host: peer0.vendor.tpsr.com
        Port: 7051

  - &SecurityOrg
    Name: SecurityOrg
    ID: SecurityMSP
    MSPDir: crypto-config/peerOrganizations/security.tpsr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('SecurityMSP.admin', 'SecurityMSP.peer', 'SecurityMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('SecurityMSP.admin', 'SecurityMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('SecurityMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('SecurityMSP.member')"
    AnchorPeers:
      - Host: peer0.security.tpsr.com
        Port: 8051

  - &AuditorOrg
    Name: AuditorOrg
    ID: AuditorMSP
    MSPDir: crypto-config/peerOrganizations/auditor.tpsr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AuditorMSP.admin', 'AuditorMSP.peer', 'AuditorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('AuditorMSP.admin', 'AuditorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('AuditorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('AuditorMSP.member')"
    AnchorPeers:
      - Host: peer0.auditor.tpsr.com
        Port: 9051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  EtcdRaft:
    Consenters:
      - Host: orderer0.orderer.tpsr.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/orderer.tpsr.com/orderers/orderer0.orderer.tpsr.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/orderer.tpsr.com/orderers/orderer0.orderer.tpsr.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  TPSRGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      TPSRConsortium:
        Organizations:
          - *VendorOrg
          - *SecurityOrg
          - *AuditorOrg

  TPSRChannel:
    Consortium: TPSRConsortium
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *VendorOrg
        - *SecurityOrg
        - *AuditorOrg
      Capabilities:
        <<: *ApplicationCapabilities